CREATE DATABASE IF NOT EXISTS etc DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS 'etc'@'%' IDENTIFIED BY 'etcpass';
GRANT ALL PRIVILEGES ON etc.* TO 'etc'@'%';

FLUSH PRIVILEGES;

